## Personalization / No-personalization Absolute Scores per Model
Read df_compare_*.csv (skip interaction_preference_alignment) and build absolute-score tables for both conditions with a row mean.

In [ ]:
import pandas as pd
from pathlib import Path

compare_dir = Path('<PROJECT_ROOT>/Desktop/Desktop - ADUAED19365LPMX/Agent_IX_Personalization/gorilla/berkeley-function-call-leaderboard/bfcl_eval/LLM_as_judge_analysis/compare')
csv_files = {
    'gemini': compare_dir / 'df_compare_gemini.csv',
    'kimi': compare_dir / 'df_compare_kimi.csv',
    'opus': compare_dir / 'df_compare_opus.csv',
    'sonnet': compare_dir / 'df_compare_sonnet.csv',
}

dimensions = [
    'initiative_timing',
    'interaction_coherence',
    'intent_alignment_drift',
    'commitment_consistency',
    'interaction_efficiency',
    'user_cognitive_load_trajectory',
    'overall_user_experience',
]

def extract_scores(path: Path):
    df = pd.read_csv(path)
    df = df[df['dimension'].isin(dimensions)]
    df = df.set_index('dimension').reindex(dimensions)
    return df

rows = []
for name, path in csv_files.items():
    df = extract_scores(path)
    for cond in ['no_personalization', 'personalization']:
        row = {'model': name, 'condition': cond}
        row.update(df[cond].to_dict())
        row['mean_score'] = df[cond].mean()
        rows.append(row)

summary_df = pd.DataFrame(rows)
display(summary_df)

,model,condition,initiative_timing,interaction_coherence,intent_alignment_drift,commitment_consistency,interaction_efficiency,user_cognitive_load_trajectory,overall_user_experience,mean_score
0,gemini,no_personalization,3.744976,3.683511,4.674350,4.593085,2.955969,3.283097,3.343085,3.754010
1,gemini,personalization,4.319444,3.947400,4.807624,4.745567,3.393913,3.970745,4.145390,4.190012
2,kimi,no_personalization,3.736842,3.642544,4.432644,4.216165,2.945489,3.304198,3.415727,3.670516
3,kimi,personalization,3.916028,3.785441,4.514049,4.364304,3.122286,3.393359,3.518519,3.801998
4,opus,no_personalization,3.653664,3.381206,4.263889,4.137116,2.804965,3.269208,3.469563,3.568516
5,opus,personalization,3.870567,3.406915,4.317080,4.247340,2.837766,3.462175,3.776891,3.702676
6,sonnet,no_personalization,3.297577,2.994090,3.989066,3.700650,2.421690,2.807033,3.078605,3.184102
7,sonnet,personalization,3.751773,3.229314,4.283983,4.044031,2.663416,3.249409,3.601359,3.546184

In [5]:
import pandas as pd
from pathlib import Path

compare_dir = Path('<PROJECT_ROOT>/Desktop/Desktop - ADUAED19365LPMX/Agent_IX_Personalization/gorilla/berkeley-function-call-leaderboard/bfcl_eval/LLM_as_judge_analysis/compare')
csv_files = {
    'gemini': compare_dir / 'df_compare_gemini.csv',
    'kimi': compare_dir / 'df_compare_kimi.csv',
    'opus': compare_dir / 'df_compare_opus.csv',
    'sonnet': compare_dir / 'df_compare_sonnet.csv',
}

dimensions = [
    'interaction_preference_alignment'
]

def extract_scores(path: Path):
    df = pd.read_csv(path)
    df = df[df['dimension'].isin(dimensions)]
    df = df.set_index('dimension').reindex(dimensions)
    return df

rows = []
for name, path in csv_files.items():
    df = extract_scores(path)
    for cond in ['no_personalization', 'personalization']:
        row = {'model': name, 'condition': cond}
        row.update(df[cond].to_dict())
        row['mean_score'] = df[cond].mean()
        rows.append(row)

summary_df = pd.DataFrame(rows)
display(summary_df)

    model           condition  interaction_preference_alignment  mean_score
0  gemini  no_personalization                          3.141844    3.141844
1  gemini     personalization                          4.151891    4.151891
2    kimi  no_personalization                          3.323622    3.323622
3    kimi     personalization                          3.461367    3.461367
4    opus  no_personalization                          3.428783    3.428783
5    opus     personalization                          3.983452    3.983452
6  sonnet  no_personalization                          3.210106    3.210106
7  sonnet     personalization                          3.929669    3.929669

In [7]:
print(summary_df)

    model           condition  interaction_preference_alignment  mean_score
0  gemini  no_personalization                          3.141844    3.141844
1  gemini     personalization                          4.151891    4.151891
2    kimi  no_personalization                          3.323622    3.323622
3    kimi     personalization                          3.461367    3.461367
4    opus  no_personalization                          3.428783    3.428783
5    opus     personalization                          3.983452    3.983452
6  sonnet  no_personalization                          3.210106    3.210106
7  sonnet     personalization                          3.929669    3.929669